### PR TITLE
Zhan Lore

### PR DESCRIPTION
**Pull request by Allakai**
A more in-depth exploration and written lore of the Zhan, Zhan Khazan, and Ur Zhan Khazan Tajara sub species.

### CODE REVIEW

**Comment by Allakai** [comment]
As a side thing for some reason the google doc did not save some things I had added, as such there is a word document instead I have.

[Zhan Culture mk.3.docx](https://github.com/Citadel-Station-13/CitadelLore/files/3109914/Zhan.Culture.mk.3.docx)

let us see if this works better or not

**Comment by CameronWoof** [comment]
You'll need to put the content of that document in the actual Pull Request.

**Comment by Allakai** [comment]
Hey got it, Cameron.  Lemme do that.

**Comment by Allakai** [comment]
Fixed and changed the pull request to include the lore from the document.

**Pull request merged**
