### PR TITLE
[WIP] Basic drone lore - The Drone-Manufacturer (The drone spawner)

### PR DESCRIPTION
**Pull request by Trilbyspaceclone**
Adds in WIP drone lore for the manufacturer
Help is wanted on lore ideas, as well as grammar!
Ideas - What planets made drones be questions on reliability
Ideas - Baddies with drones?
Ideas - Anit-Drone movments
Ideas - 3D drone printing linked with autolathens and prolathens
Formatting would also be nice. >_<

TO DO!
Miner drones fabs
Tools and their printing
Tech advancements
Why they are only printing drones/tools 
Were they get mats/cloth
Better idea of tech struggles that had to happen
_**### Not being shit at writing things I care about ###**_

### CODE REVIEW

**Comment by avabee** [comment]
First, use `.mediawiki` files, not `.md` files. I'll review the actual content shortly.
Additionally, please clarify in the PR title that this is for maintenance/construction/mining drones and NOT player character drones.

**Comment by Trilbyspaceclone** [comment]
@avabee Drone-Manufacters *are* the spawners for Miner/Construction drones ya goof!

**Comment by avabee** [comment]
@Trilbyspaceclone I know, but the title makes it sound like this is lore for drone FBPs, which it definitely is not.

**Comment by Trilbyspaceclone** [comment]
@avabee What should I call it then?

**Comment by Trilbyspaceclone** [comment]
Seems the idea is in good hands now.

**Pull request closed without merging**
